// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	file "snd-cli/pkg/cmd/util/file"

	mock "github.com/stretchr/testify/mock"
)

// FileServiceFactory is an autogenerated mock type for the FileServiceFactory type
type FileServiceFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: path
func (_m *FileServiceFactory) Execute(path string) (file.File, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 file.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (file.File, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) file.File); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(file.File)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileServiceFactory creates a new instance of FileServiceFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileServiceFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileServiceFactory {
	mock := &FileServiceFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
