package auth

import (
	"fmt"
	"github.com/MakeNowJust/heredoc"
	"github.com/spf13/cobra"
	"log"
	"snd-cli/pkg/cmd/util/token"
	"snd-cli/pkg/cmdutil"
)

var env, provider string

func NewCmdAuth(authServiceFactory *cmdutil.AuthServiceFactory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Get internal authorization token",
		Long:  "Retrieve the internal authorization token generated by Boxer by providing an authentication provider",
		Example: heredoc.Doc(`
			$ snd login -a azuread -e test
			$ snd login --auth-provider azuread --env production
		`),
		GroupID: "auth",
		Args:    cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			authService, err := authServiceFactory.CreateAuthService(env, provider)
			if err != nil {
				log.Fatalf("Failed to initialize auth service: %v", err)
			}
			return loginRun(authService)
		},
	}

	cmd.PersistentFlags().StringVarP(&env, "env", "e", "test", "Target environment")
	cmd.PersistentFlags().StringVarP(&provider, "auth-provider", "a", "azuread", "Specify the OAuth provider name")

	return cmd
}

func loginRun(authService token.AuthService) error {
	tokenProvider := token.NewProvider(authService)
	cachedToken, err := tokenProvider.GetToken() // Fetch and cache the token.
	if err != nil {
		log.Fatalf("Unable to get the token: %v", err)
	}
	fmt.Println("Login successful.")
	fmt.Println("Token:", cachedToken)
	return nil
}
