name: Publish snd-cli image to GitHub public registry
run-name: Publish ${{github.ref_name}} by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: Snd-Cli-Go
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
            
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: '1.21'
          project_path: "./cmd/snd-cli"
          binary_name: "snd-${{ matrix.goos }}-${{ matrix.goarch }}"
          extra_files: README.md