name: Publish snd-cli image to GitHub public registry
run-name: Publish ${{github.ref_name}} to GitHub registry by @${{ github.actor }}

on: workflow_dispatch

env:
  PROJECT_NAME: Snd-Cli-Go
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release_container_image:
    name: Release container image

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout head commit
        if: ${{ github.ref != 'refs/heads/main' && always() }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        name: Checkout main
        if: ${{ github.ref == 'refs/heads/main' && always() }}
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get project version
        uses: SneaksAndData/github-actions/generate_version@v0.1.9
        id: version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
        with:
          use: true
          platforms: linux/amd64

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          file: .container/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
