name: Publish snd-cli image to GitHub public registry
run-name: Publish ${{github.ref_name}} to GitHub registry by @${{ github.actor }}

on: 
  pull_request:
    branches:
      - '**'

env:
  PROJECT_NAME: Snd-Cli-Go
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release_snd_cli_binary:
    name: Release Snd-cli binary

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]
        
    steps:
      - uses: actions/checkout@v4
        name: Checkout head commit
        if: ${{ github.ref != 'refs/heads/main' && always() }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        name: Checkout main
        if: ${{ github.ref == 'refs/heads/main' && always() }}
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get project version
        uses: SneaksAndData/github-actions/generate_version@v0.1.9
        id: version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup environment variables
        run: |
          echo "GOOS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          
      - name: Build Go binary
        run: |
          version=$(git describe --tags --abbrev=7)
          go build -ldflags="-X 'snd-cli/cmd.Version=$version'" -o snd-${{ matrix.os }}-${{ matrix.arch }} ./cmd/snd-cli
      
      - name: Archive binary
        run: tar -czvf snd-${{ matrix.os }}-${{ matrix.arch }}.tar.gz snd-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ghcr.io/sneaksanddata/
          asset_path: snd-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_name: snd-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip